/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cafetera;
import javax.swing.JOptionPane;

/**
 *
 * @author DanielDeJesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cafetera c;
    public Principal() {
        initComponents();
        txtCantidadActual.setEditable(true);
        txtCapacidadMaxima.setEditable(true);
        txtModificacionCafetera.setEditable(false);
        cmdCrear.setEnabled(true);
        cmdCrearAutomatico.setEnabled(true);
        cmdAgregar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdLlenarCafetera.setEnabled(false);
        cmdVaciarCafetera.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCapacidadMaxima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        cmdCrear = new javax.swing.JButton();
        cmdCrearAutomatico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtModificacionCafetera = new javax.swing.JTextField();
        cmdAgregar = new javax.swing.JButton();
        cmdServir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmdLlenarCafetera = new javax.swing.JButton();
        cmdVaciarCafetera = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Taller Objetos 6");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Cafetera"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Capacidad máxima:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(txtCapacidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, -1));

        jLabel3.setText("Cantidad actual:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel2.add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 60, -1));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cmdCrearAutomatico.setText("C. Auto");
        cmdCrearAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrearAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificacion Cafetera"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Agregar o servir cafe:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPanel3.add(txtModificacionCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cmdServir.setText("Servir");
        cmdServir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdServir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 220, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mas Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLlenarCafetera.setText("LLenar C.");
        cmdLlenarCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarCafeteraActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenarCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        cmdVaciarCafetera.setText("Vaciar C.");
        cmdVaciarCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVaciarCafeteraActionPerformed(evt);
            }
        });
        jPanel4.add(cmdVaciarCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 220, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 210, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 240, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(563, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int capacidadM, cantidadA;
        if(txtCapacidadMaxima.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la capacidad maxima", "Error", JOptionPane.ERROR_MESSAGE);
            txtCapacidadMaxima.requestFocusInWindow();
        }
        else if(Integer.parseInt(txtCapacidadMaxima.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La capacidad maxima no puede ser cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtCapacidadMaxima.requestFocusInWindow();
            txtCapacidadMaxima.selectAll();
        }
        else if(txtCantidadActual.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la cantidad actual", "Error", JOptionPane.ERROR_MESSAGE);
            txtCantidadActual.requestFocusInWindow();
        }
        else{
            try{
                    capacidadM = Integer.parseInt(txtCapacidadMaxima.getText());
                    cantidadA = Integer.parseInt(txtCantidadActual.getText());
                    c = new Cafetera(capacidadM,cantidadA);
                    JOptionPane.showMessageDialog(this, "Cafetera creada exitosamente");
                    
                    txtCantidadActual.setEditable(false);
                    txtCapacidadMaxima.setEditable(false);
                    txtModificacionCafetera.setEditable(true);
                    cmdCrear.setEnabled(false);
                    cmdCrearAutomatico.setEnabled(false);
                    cmdAgregar.setEnabled(true);
                    cmdServir.setEnabled(true);
                    cmdLlenarCafetera.setEnabled(true);
                    cmdVaciarCafetera.setEnabled(true);
                    cmdMostrar.setEnabled(true);
                    cmdLimpiar.setEnabled(true);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Valor no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        String aux;
            aux=c.mostrar();
            txtResultado.setText(aux);
        
            cmdCrear.setEnabled(false);
            cmdCrearAutomatico.setEnabled(false);
            cmdAgregar.setEnabled(true);
            cmdServir.setEnabled(true);
            cmdLlenarCafetera.setEnabled(true);
            cmdVaciarCafetera.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
        
            
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        int modificadorCafetera;
        if(txtModificacionCafetera.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el N° de tazas a agregar", "Error", JOptionPane.ERROR_MESSAGE);
            txtModificacionCafetera.requestFocusInWindow();
        }
        else{
            try{
                modificadorCafetera = Integer.parseInt(txtModificacionCafetera.getText());
                c.agregarCafe(modificadorCafetera);
                txtResultado.setText("La cantidad actual es de: "+c.getCantidadActual());
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Valor no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cmdCrear.setEnabled(false);
        cmdCrearAutomatico.setEnabled(false);
        cmdAgregar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdLlenarCafetera.setEnabled(true);
        cmdVaciarCafetera.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdServirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServirActionPerformed
        int modificadorCafetera;
        String aux;
        if(txtModificacionCafetera.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el N° de tazas a servir", "Error", JOptionPane.ERROR_MESSAGE);
            txtModificacionCafetera.requestFocusInWindow();
        }
        else{
            try{
                modificadorCafetera = Integer.parseInt(txtModificacionCafetera.getText());
                aux = c.servirTaza(modificadorCafetera);
                txtResultado.setText(""+aux);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Valor no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cmdCrear.setEnabled(false);
        cmdCrearAutomatico.setEnabled(false);
        cmdAgregar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdLlenarCafetera.setEnabled(true);
        cmdVaciarCafetera.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdServirActionPerformed

    private void cmdLlenarCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarCafeteraActionPerformed
        c.llenarCafetera();
        cmdCrear.setEnabled(false);
        cmdCrearAutomatico.setEnabled(false);
        cmdAgregar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdLlenarCafetera.setEnabled(true);
        cmdVaciarCafetera.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdLlenarCafeteraActionPerformed

    private void cmdVaciarCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVaciarCafeteraActionPerformed
        c.vaciarCafetera();
        cmdCrear.setEnabled(false);
        cmdCrearAutomatico.setEnabled(false);
        cmdAgregar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdLlenarCafetera.setEnabled(true);
        cmdVaciarCafetera.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdVaciarCafeteraActionPerformed

    private void cmdCrearAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearAutomaticoActionPerformed
        c = new Cafetera();
        JOptionPane.showMessageDialog(this, "Cafetera creada exitosamente");
                txtCantidadActual.setEditable(false);
                txtCapacidadMaxima.setEditable(false);
                txtModificacionCafetera.setEditable(true);
                cmdCrear.setEnabled(false);
                cmdCrearAutomatico.setEnabled(false);
                cmdAgregar.setEnabled(true);
                cmdServir.setEnabled(true);
                cmdLlenarCafetera.setEnabled(true);
                cmdVaciarCafetera.setEnabled(true);
                cmdMostrar.setEnabled(true);
                cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdCrearAutomaticoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtCantidadActual.setText("");
        txtCapacidadMaxima.setText("");
        txtModificacionCafetera.setText("");
        txtResultado.setText("");
        txtCantidadActual.setEditable(true);
        txtCapacidadMaxima.setEditable(true);
        txtModificacionCafetera.setEditable(false);
        cmdCrear.setEnabled(true);
        cmdCrearAutomatico.setEnabled(true);
        cmdAgregar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdLlenarCafetera.setEnabled(false);
        cmdVaciarCafetera.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdCrearAutomatico;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenarCafetera;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdServir;
    private javax.swing.JButton cmdVaciarCafetera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtModificacionCafetera;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
